---
title: "The dimensions of Coherence"
author: "Viviane Schneider"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: zenburn
    theme: cerulean
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=TRUE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


# The Coherence Dimensions
Contextual coherence index is a scale from 0 to 1. It aims to measure the alignment between cultural symbolic agreements, values and concepts negotiation.  Equation to calculate this index is present in follow Equation 1, where:

*Rf is Referenciality,
*RC is Receptivity,
*Pr is Presccritivity,
SoU is Sense of Unity.

$Cc=Rf+Rc+Pr+SoU$

In the next sections are presents some examples.

# Referenciality (Rf)
Coherence of Referentiality (Rf) is a dimension in CoheNet Metamodel [3], which represents into a scale from 0 to 1(max), the quality of socio-technical arrangement referential. It aims to measure the virtual described robustness of the symbolic referential, such as, social contract, culture, norms, ideas, common goals, etc., of a particular community. In CoheNet Metamodel (2019) [3] the referential index Referenciality (Rf) is calculated by the following formula, where RCC is the indicators set that represents Referential Common Contract elements, RCP is the Referential Cultural Perspective elements set, and RP is the Referential Policies elements set. RCC, RCP and RP are metadata set, which represents the indicators mean, stablish from metadata architecture guidelines, by arrangement manager, data scientist, knowledge engineer, or/and group members.

$Rf=RCC+RCP+RP$

# Receptivity (Rc)

Receptivity (Rc) is a coherence dimension such represents into a scale from 0 to 1 (max), how much the referential of a socio-technical arrangement (roles, policies, culture and symbolic hierarchy) are accepted by agents. Into follow formula Equation 1, Mode Metadata Structure (M) has follow indicators which represents quality: 
* Role_in_Exchange (RiE), Goods-&-Services (G&S), Information (Inf), Proposal (Giv), Proposition (Dem), Discussed Topic (DT), Consensus Negotiation (CN) [3].  RCC, RCP and RP are metadata set, which represents the indicators mean, stablish from metadata architecture guidelines, by arrangement manager, data scientist, knowledge engineer, or/and group members.

$Rc=(RiE+G&S+Inf+Giv+Dem+DT+CN) / 7$

# Prescritivity (Pr)

Prescritivity (Pr) is a coherence dimensions such represents into a scale from 0 to 1 (max). Its measure the quality of agent actions, compared with socio-technical context references. The formula Eq. 9, describe elements from Situational Norms (SNo) Metadata Structure such as, Situational_Norms_Coproduction (SNCo) and Situational Norms Comprehensiveness (SNC). SNCo, SNC are metadata set, which represents the indicators mean, stablish from metadata architecture guidelines, by arrangement manager, data scientist, knowledge engineer, or/and group members [3].  

$Pr=(SNCo+SNC)/2$ 

# Sense of Unity (SoU)

Sense of unity (SoU) is a coherence dimensions such represents into a scale from 0 to 1 (max), the communication convergence of a socio-technical arrangement. Into follow formula Eq. 8, elements represents quality of semantic convergence through the follow indicators described into Situational Negotiation (SN) Metadata Structure: Mode Field Attributes Set  - Accessibility production (MFAZ1), Mode Field Attributes Set - Historical (MFAZ2), Mode Field Attributes Set - Security (MFAZ3), Mode Field Attributes Set - Learning (MFAZ4),   Mode_Tenor_Members – Content coproduction group (MTM1), Mode_Tenor_Members – Correlation of Workflow (MTM2), [3].  MFAZ1, MFAZ2, MFAZ3, MFAZ4, MTM1, MTM2 are metadata set, which represents the indicators mean, stablish from metadata architecture guidelines, by arrangement manager, data scientist, knowledge engineer or/and group members.

$SoU=(MFAZ1+MFAZ2+MFAZ3+MFAZ4+MTM1+MTM2)/6$

